#!/bin/sh
cd "${0%/*}" || exit                                # Run from this directory
. ${WM_PROJECT_DIR:?}/wmake/scripts/AllwmakeParseArguments
#------------------------------------------------------------------------------

# Make libraries
wmake $targetType src

# Make Application
wmake $targetType applications/rocketMotor

# Make Utilities
wmake $targetType utilities/postProcessRocket
wmake $targetType utilities/mapVolFields
wmake $targetType utilities/rocketConservation
wmake $targetType utilities/setRocketInitField
